import './globals.css';

import Navbar from '../components/Navbar';
import { AuthProvider } from '@/lib/context/AuthContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body>
        <AuthProvider>
          <div className="container mx-auto">
            <Navbar />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
